apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-app-config
data:
  app-config: |-
    polaris-dashboard:
      host: 0.0.0.0
      port: 8001
      debug: False
    goldilocks:
      host: 0.0.0.0
      port: 8002
      debug: False
