version: 1.0.0
apiVersion: v2
name: gitops-app-set

metadata:
  name: gitops-app-set
  description: A set of applications including Polaris Dashboard and Goldilocks

resources:
  - name: gitops-app-config
    configMap:
      name: gitops-app-config

templates:
  - name: configmap.yaml
    configMap:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: gitops-app-config
      data:
        app-config: |-
          polaris-dashboard:
            host: 0.0.0.0
            port: 8001
            debug: False
          goldilocks:
            host: 0.0.0.0
            port: 8002
            debug: False

  - name: polaris-dashboard
    deployment:
      name: polaris-dashboard
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: polaris-dashboard
        template:
          metadata:
            labels:
              app: polaris-dashboard
          spec:
            containers:
              - name: polaris-dashboard
                image: arielbenzikri/devops-example-job:dev
                imagePullPolicy: Always
                ports:
                  - containerPort: 8001
                readinessProbe:
                  httpGet:
                    path: /
                    port: 8001
  - name: goldilocks
    deployment:
      name: goldilocks
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: goldilocks
