version: 1.0
apiVersion: v2
name: my-app

# The chart's metadata
metadata:
  name: my-app
  version: 0.1.0
  description: A simple Flask app with Redis

# The chart's resources
resources:
- name: my-app-config
  configMap:
    name: my-app-config
    items:
    - key: app-config
      path: config.yaml

# The chart's templates
templates:
- name: my-app-deployment
  deployment:
    name: my-app-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: my-app
      template:
        metadata:
          labels:
            app: my-app
        spec:
          containers:
          - name: my-app
            image: my-app:latest
            imagePullPolicy: Always
            ports:
            - containerPort: 8000
            envFrom:
            - configMapRef:
                name: my-app-config
            readinessProbe:
              httpGet:
                path: /
                port: 8000
