apiVersion: v2
name: url-shortner
description: Helm chart for a Django-based URL shortener app

# Chart metadata
version: 0.1.0
appVersion: 1.0.0

# Chart dependencies
dependencies:
  - name: postgresql
    version: 9.6.16
    repository: https://kubernetes-charts.storage.googleapis.com/

# Container images
image:
  repository: myregistry.com/url-shortner
  tag: latest

# Resources
resources:
  limits:
    memory: 256Mi
    cpu: 1000m

# Service and Ingress
service:
  name: url-shortner
  port: 8000
  type: ClusterIP
  externalPort: 8000

ingress:
  enabled: true
  path: /

# Values for Django and PostgreSQL
values:
  django:
    image:
      repository: myregistry.com/url-shortner
      tag: latest
    env:
      - name: DEBUG
        value: "True"
    secret:
      - name: SECRET_KEY
        value: SECRET_KEY
  postgresql:
    postgresqlUsername: urlshortner
    postgresqlPassword: urlshortnerpassword
    postgresqlDatabase: urlshortner
