name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Bump version
      run: |
        version=$(date +%s)
        echo "version: $version" > version.txt
    - name: Build the Docker image
      run: |
        version=$(cat version.txt | awk '{print $2}')
        docker build . --file Dockerfile --tag my-image-name:$version
    - name: Update Helm chart
      run: |
        version=$(cat version.txt | awk '{print $2}')
        helm upgrade my-chart . --set image.tag=$version --reuse-values
