name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}


    - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

    - name: Build and Push Dockerfile
      run: |
        docker build -t my-image -f Dockerfile .
        docker tag my-image:latest 538843831727.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-image:latest
        docker push 538843831727.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/my-image:latest

    - name: Update Version of Helm Chart
      run: |
        helm init
        awk -F: '{ if ($1=="version") {print "version: " $2+1} else {print $0} }' Chart.yaml > Chart.yaml.tmp && mv Chart.yaml.tmp Chart.yaml
        helm upgrade --reuse-values my-chart helm/chart.yml
